### ISSUE TITLE
Stack trace in the console when validating spec

### ISSUE THREAD

**Issue by JFCote** [jrouly/sbt-openapi-style-validator#3]
Here is the console log when validating the [petstore.json](https://petstore.swagger.io/v2/swagger.json) spec. The `*ERROR*` are normal but the stack trace should not be there. I'm using version 0.0.2.

```
C:\dev\CS\CSBackEnd>sbt openApiStyleValidate
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_201)
[info] loading global plugins from C:\Users\jcote\.sbt\1.0\plugins
[info] loading settings for project csbackend-build from plugins.sbt ...
[info] loading project definition from C:\dev\CS\CSBackEnd\project
[info] loading settings for project root from build.sbt ...
[info] set current project to S360ControlSite (in build file:/C:/dev/CS/CSBackEnd/)
[error] java.lang.RuntimeException: OpenAPI specification style validation failed.
[error] *ERROR* in path POST /pet/{petId}/uploadImage 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path /pet/{petId}/uploadImage 'uploadImage' -> path should be in hyphen-case
[error] *ERROR* in path /pet/findByStatus 'findByStatus' -> path should be in hyphen-case
[error] *ERROR* in path /pet/findByTags 'findByTags' -> path should be in hyphen-case
[error] *ERROR* in path GET /pet/{petId} 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path POST /pet/{petId} 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path DELETE /pet/{petId} 'api_key' -> header should be in hyphen-case
[error] *ERROR* in path DELETE /pet/{petId} 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path GET /store/order/{orderId} 'orderId' -> parameter should be in hyphen-case
[error] *ERROR* in path DELETE /store/order/{orderId} 'orderId' -> parameter should be in hyphen-case
[error] *ERROR* in path /user/createWithArray 'createWithArray' -> path should be in hyphen-case
[error] *ERROR* in path /user/createWithList 'createWithList' -> path should be in hyphen-case
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at org.openapitools.openapistylevalidator.sbt.plugin.tasks.OpenApiStyleValidateTask.$anonfun$openApiStyleValidateTask$1(OpenApiStyleValidateTask.scala:15)
[error]         at org.openapitools.openapistylevalidator.sbt.plugin.tasks.OpenApiStyleValidateTask.$anonfun$openApiStyleValidateTask$1$adapted(OpenApiStyleValidateTask.scala:9)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (openApiStyleValidate) OpenAPI specification style validation failed.
[error] *ERROR* in path POST /pet/{petId}/uploadImage 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path /pet/{petId}/uploadImage 'uploadImage' -> path should be in hyphen-case
[error] *ERROR* in path /pet/findByStatus 'findByStatus' -> path should be in hyphen-case
[error] *ERROR* in path /pet/findByTags 'findByTags' -> path should be in hyphen-case
[error] *ERROR* in path GET /pet/{petId} 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path POST /pet/{petId} 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path DELETE /pet/{petId} 'api_key' -> header should be in hyphen-case
[error] *ERROR* in path DELETE /pet/{petId} 'petId' -> parameter should be in hyphen-case
[error] *ERROR* in path GET /store/order/{orderId} 'orderId' -> parameter should be in hyphen-case
[error] *ERROR* in path DELETE /store/order/{orderId} 'orderId' -> parameter should be in hyphen-case
[error] *ERROR* in path /user/createWithArray 'createWithArray' -> path should be in hyphen-case
[error] *ERROR* in path /user/createWithList 'createWithList' -> path should be in hyphen-case
[error] Total time: 1 s, completed Feb 23, 2021 12:00:26 PM
```

Here is the configuration in the `build.sbt`

```
lazy val root = (project in file("."))
    .enablePlugins(OpenApiStylePlugin)
    .settings(openApiStyleSpec := file("openapi/petstore.json"))
    .settings(openApiStyleConfig := Some(file("openapi/style-options.json")))
```

Here is the content of `style-options.json`

```
{
  "validateInfoLicense": true,
  "validateInfoDescription": true,
  "validateInfoContact": true,

  "validateOperationOperationId": true,
  "validateOperationDescription": false,
  "validateOperationTag": true,
  "validateOperationSummary": true,

  "validateModelPropertiesExample": false,
  "validateModelNoLocalDef": true,

  "validateNaming": true,
  "ignoreHeaderXNaming": true,
  "pathNamingConvention": "HyphenCase",
  "parameterNamingConvention": "HyphenCase",
  "headerNamingConvention": "HyphenCase",
  "propertyNamingConvention": "CamelCase"
}
```

**Comment by jrouly** [comment]
Thanks for filing. The stack trace is because of how I am instructing SBT to mark the task as a failure using `sys.error` (`throw new RuntimeException`): https://github.com/jrouly/sbt-openapi-style-validator/blob/master/src/main/scala/org/openapitools/openapistylevalidator/sbt/plugin/tasks/OpenApiStyleValidateTask.scala#L15

Why the stack trace is _in the middle_ of your error report, I'm not sure. Probably just a logger concurrency blip.

Either way, the stack trace is not super attractive here. I'll look into alternative methods of causing task failure _without_ an exception.
